### ISSUE TITLE
Add button to stop/pause audio button playback

### ISSUE THREAD

**Issue by bryanbarcos** [mdanialqureshi/TalkBox#2]
No button available for stop/pause. Once an audio file is played, the only way to stop it is to close the entire app.

**Comment by xmbhasin** [comment]
Resolved in 404d1b02f627.

Users can now stop audio playback via a dedicated button. We will not be adding pause and resume functionality for now as we expect audio clips used with TalkBox will be short in duration.

**Comment by xmbhasin** [comment]
Resolved #2 in 404d1b02f627.

Users can now stop audio playback via a dedicated button. We will not be adding pause and resume functionality for now as we expect audio clips used with TalkBox will be short in duration.
