### ISSUE TITLE
Cannot See any Audio Files

### ISSUE THREAD

**Issue by Dhruv9979** [mdanialqureshi/TalkBox#3]
Product - Configuration App
• Version - Midterm Release
• Component - Profile Component
• Platform - Intellij IDEA
• OS - Windows 10
• JVM - java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

Severity Bug:
Enhancement - Request for enhancement, ideas 
Major - major loss of function
Priority : P1

Summary - The number of the audio or what audio files that the user has saved cannot be seen in the App. 
Description -  You can show a list or a window showing all the audio files that the user has and added using the recording feature, so he has clear idea what he has, and also he can select if he wants to assign an existing audio file to a button in the Simulator App.

**Comment by xmbhasin** [comment]
We have added audio file uploading via dedicated button and via drag and drop. We will not add an audio file list as it would clutter the interface. 

The user can label and add icons to audio buttons to remember which audio files are associated with which buttons. The user can also view the TalkBoxData folder which contains all audio files in a well-organized manner if necessary.
